### ISSUE TITLE
权限打不开  界面很简陋

### ISSUE THREAD

**Issue by CYL-ALing** [gemgao/redenvelopes#1]
无障碍权限打不开

**Comment by gemgao** [comment]
打不开？提供下截图和手机型号吧，界面的话，，，欢迎各位ui大佬提供切图

**Comment by CYL-ALing** [comment]
三星s10e



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gem"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 下午3:04
收件人: "gemgao/redenvelopes"<redenvelopes@noreply.github.com&gt;; 
抄送: "爱"<1092723495@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gemgao/redenvelopes] 权限打不开  界面很简陋 (#1)




打不开？提供下截图和手机型号吧，界面的话，，，欢迎各位ui大佬提供切图

**Comment by gemgao** [comment]
我手头没有这个机型，你可以手动打开，当然欢迎你适配一下，提pr

**Comment by CYL-ALing** [comment]
是打开&nbsp; 回去页面又是关的&nbsp; 再进去打开 再回去&nbsp; 还是关的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gem"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 下午3:09
收件人: "gemgao/redenvelopes"<redenvelopes@noreply.github.com&gt;; 
抄送: "爱"<1092723495@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gemgao/redenvelopes] 权限打不开  界面很简陋 (#1)




我手头没有这个机型，你可以手动打开，当然欢迎你适配一下，提pr

**Comment by gemgao** [comment]
哦，你说的是页面显示哦，有的手机打开没有通知，或者通知的方法不一样，页面就刷新不了显示，但是只要你确保打开了，不影响使用的

**Comment by CYL-ALing** [comment]
不是显示哦&nbsp; &nbsp;设置里面的无障碍也是关闭的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gem"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 下午3:14
收件人: "gemgao/redenvelopes"<redenvelopes@noreply.github.com&gt;; 
抄送: "爱"<1092723495@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gemgao/redenvelopes] 权限打不开  界面很简陋 (#1)




哦，你说的是页面显示哦，有的手机打开没有通知，或者通知的方法不一样，页面就刷新不了显示，但是只要你确保打开了，不影响使用的

**Comment by gemgao** [comment]
设置里面手动也打不开？那应该是手机系统的问题，主要是我没有你这个设备，不然我调试一下，你也可以适配一下，提个pr，我这边的手机都是好的，OPPOR9,华为v9,小米9，华为v8
