### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by 2daye** [gemgao/redenvelopes#11]
就是不知道，是安卓微信通知有bug，还是怎么的，只要当前聊天窗口是从红包页面退出来的，这个时候，如果有另外的群发红包，或者另外的人给你发红包，也别说发红包了，就是给你发消息，安卓的通知中心会没有消息，这也就知道你的个从通知中心获取消息的思路不能进行下去，不知大佬有没有办法在这种情况做一下优化，从抢好红包的界面，退出2次，直接退到聊天列表

**Comment by gemgao** [comment]
我刚刚测试了我的小米10，在一个聊天页面，别的人发消息过来是有通知的呀。不知道你说的是不是这个问题

**Comment by 2daye** [comment]
你要在当前聊天页面，拆一次红包，从红包页面退回到当前聊天页面，这个时候，其他群或者个人，给你发消息，就没通知了，就必须在当前页面进行一次拆红包，或者点进拆过的红包也可以，在退回当前页面

**Comment by 2daye** [comment]
我的是小米9

**Comment by gemgao** [comment]
没发现问题，微信通知是微信系统的，我们app控制不了
