### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by haofengsiji** [gemgao/redenvelopes#2]
建议大佬，把apk文件单独链接出来。
第一次来不知道在哪里下载，今天想起来了，又找了几下，才找到。

不过
华为V9，微信7.0.9，亲测可用
谢谢大佬更新，也快过年了，祝新年快乐！

**Comment by jackystef** [comment]
> 
> 
> 建议大佬，把apk文件单独链接出来。
> 第一次来不知道在哪里下载，今天想起来了，又找了几下，才找到。
> 
> 不过
> 华为V9，微信7.0.9，亲测可用
> 谢谢大佬更新，也快过年了，祝新年快乐！

在哪里找啊

**Comment by jackystef** [comment]
锁屏，可以抢红包不

**Comment by gemgao** [comment]
如果找不到，提供了代码可以自己编译哦，如果把链接放出来，怕腾讯法务哈哈
