### ISSUE TITLE
hello啊，兄弟，原先你的红包软件很好用，后来就用不了了，什么情况？

### ISSUE THREAD

**Issue by liqingju8096** [gemgao/redenvelopes#3]
华为 p10，刚开始很好使用，后来没反应了。

**Comment by gemgao** [comment]
后来？是微信更新版本了，你也要对应的更新我的版本，目前适配到7.0.10

**Comment by liqingju8096** [comment]
3Q

gem <notifications@github.com> 于2020年2月3日周一 上午11:27写道：
