### ISSUE TITLE
支持后台运行抢嘛

### ISSUE THREAD

**Issue by suiyingsky** [gemgao/redenvelopes#4]
能支持就更好了，按原理来是可以实现的吗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by gemgao** [comment]
后台运行是什么意思？没有打开微信的时候？现在是支持的，只要你手机通知栏有微信红包这个提示，但是现在高版本有的手机通知栏不会出现具体的聊天信息，只是提示有一个通知，无法判断是不是红包，这个目前我还没想到怎么破解
