### ISSUE TITLE
抢红包执行流程无法闭环

### ISSUE THREAD

**Issue by xlkm** [gemgao/redenvelopes#5]
HI，刚用上你的抢红包软件，非常好用，然后有些建议

1、抢到红包后，建议能够自动退到手机主界面，而不是停留在微信界面，留在微信界面会导致一系列问题：
     问题1：如果红包出现在当前聊天群，程序将把红包点开了，没有执行拆红包及后续操作，导致红包无法正常抢到。
     问题2：如果红包出现在其他聊天群中，程序不会主动去抢红包，而是必须手动退出当前聊天群，程序才会去抢红包。
     鉴于以上两个问题，会导致无法实现程序的初步自动化循环抢红包，建议先让程序在抢到红包后，自动退出微信界面，再优化处理问题1和问题2，本人使用的测试机器是小米MX5

**Comment by gemgao** [comment]
目前只是做了在微信首页会自动点击对应聊天条-点击红包-拆红包-关闭红包页面。
你说的这个情况，只需要添加一个步骤既可以解决：关闭红包页面-关闭聊天界面到微信首页。
只要添加一行代码就可以哦。完了我有时间了支持下，当然欢迎你解决了，提pr哦
