### ISSUE TITLE
增加个是否抢自己发的红包

### ISSUE THREAD

**Issue by jeraypop** [gemgao/redenvelopes#8]
现在自己发的,如果没被抢完,一直不停的点击红包   烦哦

**Comment by gemgao** [comment]
当初写的时候只考虑了白嫖，没想到自己还会发哈哈，周末了我研究一下，搞一下

**Comment by gemgao** [comment]
@jeraypop 我试了下，在群红包里面没有发现这个情况，麻烦你给个详细步骤或者截图，谢谢了

**Comment by jeraypop** [comment]
发给个人红包，对方不领取 就会一直点     另外群红包被别人领取完，将会一直在首页和对话页面跳转
