### ISSUE TITLE
华为v30 pro 微信7.0.19无效

### ISSUE THREAD

**Issue by gustave001** [gemgao/redenvelopes#9]
按说明做的，点击“微信红包监控开关“之后，在无障碍里开启了红包权限，然后返回设置里面，“微信红包监控开关“仍然显示的是关闭状态

**Comment by gemgao** [comment]
如果确认辅助功能开了，这个还是关闭有可能要适配一下，麻烦发下系统版本号，但是抢红包功能应该可以

**Comment by gustave001** [comment]
嗯，之前我用的7.0.19的，可能是延迟的问题获取不到节点？我降到7.0.13就能用了。。。话说有空适配下目前最新的7.0.22不？

**Comment by gemgao** [comment]
都出7.0.22了？好的我抽时间适配一下

**Comment by gemgao** [comment]
小米10，昨天试了7.0.22是可以兼容的，你的不行要自己调整一下延迟时间

**Comment by gustave001** [comment]
嗯，调180可以的，谢了哈

**Comment by gemgao** [comment]
已经适配8.0.0
